service: aws-python
provider:
  name: aws
  runtime: python3.8
  timeout: 30
  memorySize: 128
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:CreateTable
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:ListStreams
          Resource: "arn:aws:dynamodb:us-east-1:*:*"
        - Effect: Allow
          Action:
            - sns:Publish
            - sns:Subscribe
          Resource: "arn:aws:sns:us-east-1:*:*"
plugins:
  - serverless-offline
custom:
  baseApi: person
functions:
  create:
    handler: create.handler
    events:
      - http:
          path: ${self:custom.baseApi}/create
          method: post
  update:
    handler: update.handler
    events:
      - http:
          path: ${self:custom.baseApi}/update/{id}
          method: put
  list:
    handler: list.handler
    events:
      - http:
          path: ${self:custom.baseApi}/list
          method: get
  show:
    handler: show.handler
    events:
      - http:
          path: ${self:custom.baseApi}/show/{id}
          method: get
  delete:
    handler: delete.handler
    events:
      - http:
          path: ${self:custom.baseApi}/delete/{id}
          method: delete
